version: "3.1"

services: 

  mongo:
    container_name: mongo
    env_file:
      - .env
    image: mongo:5.0.6
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./seed.js:/docker-entrypoint-initdb.d/mongo-init.js:ro